prodTop.wm_iconbitmap("icon.ico")
helpwindow.wm_iconbitmap("icon.ico")
window.wm_iconbitmap("icon.ico")
  logo = PhotoImage(file ="download.png")
        logoimage = Label(prodTop, image = logo)
        logoimage.place(x = 400, y = 20)
        logoimage.configure(background = "Snow")
    logo = PhotoImage(file ="download.png")
    logoimage = Label(helpwindow, image = logo)
    logoimage.place(x = 20, y = 120)
    logoimage.configure(background = "snow")
     nameTop.wm_iconbitmap("icon.ico")

        logo = PhotoImage(file ="download.png")
        logoimage = Label(nameTop, image = logo)
        logoimage.place(x = 430, y = 20)
        logoimage.configure(background = "Snow")
        part1 = PhotoImage(file ="discounts.png")
        part1image = Label(top, image = part1)
        part1image.place(x = 55, y = 130)

          top.wm_iconbitmap("icon.ico")
 logo = PhotoImage(file ="download.png")
         logo = PhotoImage(file ="download.png")
        logoimage = Label(top, image = logo)
        logoimage.place(x = 350, y = 20)
        logoimage.configure(background = "Grey")
         part1 = PhotoImage(file ="products.png")
        part1image = Label(prodTop, image = part1)
        part1image.place(x = 50, y = 140)
#Placing logo
logo = PhotoImage(file = "download.png")
logoimage = Label(image = logo)
logoimage.configure(background = "grey")
logoimage.place(x = 330, y = 50)
  part1 = PhotoImage(file ="nameboxes.png")
        part1image = Label(nameTop, image = part1)
        part1image.place(x = 50, y = 140)

